name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - {{ cookiecutter.main_branch }}
  pull_request:
    branches:
      - {{ cookiecutter.main_branch }}

{% raw -%}
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
{%- endraw %}
          - "{{ cookiecutter.go_version }}"
{%- raw %}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Lint
        run: make vet
      - name: Vuln
        run: make vuln
{%- endraw %}
